[phases.setup]
nixPkgs = ['rustup', 'gcc', 'python310', 'python310Packages.pip', 'python310Packages.virtualenv']

[phases.install]
cmds = [
  'rustup default stable',
  'virtualenv /tmp/venv',
  'source /tmp/venv/bin/activate',
  'pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'source /tmp/venv/bin/activate && python app.py'