[phases.setup]
nixPkgs = ['rustup', 'gcc', 'python310']

[phases.install]
cmds = [
  'rustup default stable',
  'python -m ensurepip --upgrade',
  'python -m pip install --upgrade pip',
  'python -m pip install -r requirements.txt'
]

[start]
cmd = 'python app.py'