[phases.setup]
nixPkgs = ['rustup', 'gcc', 'python310', 'python310Packages.pip', 'python310Packages.virtualenv']

[phases.install]
cmds = [
  'rustup default stable',
  'python -m venv /app/venv',  # Create a virtual environment
  '/app/venv/bin/pip install --no-cache-dir -r requirements.txt'  # Install dependencies
]

[start]
cmd = '/app/venv/bin/python app.py'